apiVersion: v1
kind: Service
metadata:
  name: cloud-portfolio-service
  labels:
    app: cloud-portfolio
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: cloud-portfolio
